name: 'I18n Merge'
description: 'Merge i18n translation files into one output file'
author: 'larrrssss'
inputs:
  root:
    required: false
    description: 'Change the root path for all paths'
    default: '/'
  output_file_path:
    required: false
    description: 'Path for the output file'
    default: 'output.json'
  locales_file_path:
    required: false
    description: 'Path for the root locales file'
    default: 'locales.json'
  base_file_name:
    required: false
    description: 'Name of the base file'
    default: 'base.json'
  workspace:
    required: true
    description: 'Github $GITHUB_WORKSPACE variable'
  exclude:
    required: false
    description: 'Define a glob pattern to exclude paths from merging. This is based on a specific locale directory.'
outputs:
  changes_detected:
    description: 'Wheter there are new changes'
runs:
  using: 'node16'
  main: 'dist/index.js'
